test

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -12,8 +12,16 @@ echo "${WARNING}Note: if any of these checks fail, this commit will not be pushe
 
 echo "${CHECKS}Building rust binary${NC}"
 cargo build
+RESULT=$?
+
+if [ $RESULT -ne 0 ]
+then
+  echo "${WARNING}cargo build failed! Will not push to branch${NC}"
+  exit 1
+fi
 
 echo "${CHECKS}Running tests${NC}"
 cargo test
 
 echo "${SUCCESS}Building and testing has successfully finished; pushing to central repo${NC}"
+exit 0
